### ISSUE TITLE
Changing product name doesn't produce new WMClass on KDE

### ISSUE THREAD

**Issue by perqin** [tadfisher/arch-android-studio-canary#2]
Arch Linux version:

```
$ uname -a
Linux archlinux 4.17.14-arch1-1-ARCH #1 SMP PREEMPT Thu Aug 9 11:56:50 UTC 2018 x86_64 GNU/Linux
```

Package version: 3.3.0.4

After starting Android Studio Canary, it still stays together with the icon of the stable channel on task bar. Try to get its WMClass:

```
$ xprop WM_CLASS
WM_CLASS(STRING) = "sun-awt-X11-XFramePeer", "jetbrains-studio"
```

**Comment by tadfisher** [comment]
I'm no longer maintaining this package as I don't use Arch.
